# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cells-rails/all/cells-rails.rbi
#
# cells-rails-0.1.6

module Cells
end
module Cells::Rails
end
