# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/erbse/all/erbse.rbi
#
# erbse-0.1.4

module Erbse
end
class Erbse::Parser
  def call(str); end
  def initialize(*); end
end
class Erbse::BlockFilter < Temple::Filter
  def on_capture_block(code, content_ast); end
  def on_erb_block(code, content_ast); end
end
class Erbse::Engine < Temple::Engine
end
