# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-lsp-cell/all/ruby-lsp-cell.rbi
#
# ruby-lsp-cell-0.1.0

module RubyLsp
end
module RubyLsp::Cell
end
class RubyLsp::Cell::Addon < RubyLsp::Addon
  def activate(*args, **, &blk); end
  def create_code_lens_listener(*args, **, &blk); end
  def deactivate(*args, **, &blk); end
  def initialize(*args, **, &blk); end
  def name(*args, **, &blk); end
  def version(*args, **, &blk); end
  extend T::Private::Methods
  extend Singleton
  extend T::Sig
end
