inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-sorbet
require:
 - rubocop-rake

AllCops:
  NewCops: disable
  DisplayCopNames: true
  SuggestExtensions: false
  DisabledByDefault: false

Style/StderrPuts:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
